services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: go_site
    hostname: postgres
    ports:
      - 5432:5432
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
