services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: secret
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
